import os
import zipfile
import tempfile
import uuid
from typing import Dict
from pathlib import Path
from core.logging_config import get_logger

logger = get_logger("core.project_manager")

class ProjectManager:
    """
    Handles the physical packaging of code generated by NOVA's Developer Agent.
    Converts a virtual dictionary of {filepath: content} into a downloadable ZIP archive.
    """
    def __init__(self):
        # We will store zips temporarily in the backend/data/projects directory
        self.projects_dir = Path("data/projects")
        self.projects_dir.mkdir(parents=True, exist_ok=True)

    def package_project(self, files: Dict[str, str], project_name: str = "nova_project") -> str:
        """
        Creates a ZIP file containing all the generated project files.
        Returns the absolute filepath to the generated ZIP.
        """
        zip_filename = f"{project_name}_{uuid.uuid4().hex[:8]}.zip"
        zip_filepath = self.projects_dir / zip_filename

        try:
            with zipfile.ZipFile(zip_filepath, 'w', zipfile.ZIP_DEFLATED) as zipf:
                for relative_path, content in files.items():
                    # Security: sanitize relative path to prevent directory traversal
                    clean_path = str(Path(relative_path)).replace("..", "").strip("\\/")
                    # Create the file within the zip archive
                    zipf.writestr(clean_path, content)
            
            logger.info(f"Project successfully zipped at: {zip_filepath}")
            return str(zip_filepath)
        except Exception as e:
            logger.error(f"Failed to package project: {e}")
            raise e

project_manager = ProjectManager()
